# Generated by Django 4.2.11 on 2025-11-03 18:58

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_product', to='product.products'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='product.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='searchedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searched_products', to='product.products'),
        ),
        migrations.AddField(
            model_name='searchedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seearched_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewimages',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='product.productreviewrating'),
        ),
        migrations.AddField(
            model_name='removedfromcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_removed_cart', to='product.products'),
        ),
        migrations.AddField(
            model_name='removedfromcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_removed_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvariations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='product.products'),
        ),
        migrations.AddField(
            model_name='productvariations',
            name='product_images',
            field=models.ManyToManyField(blank=True, to='product.productimage'),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_brand', to='product.branddetails'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_tag', to='product.producttags'),
        ),
        migrations.AddField(
            model_name='productreviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='product.products'),
        ),
        migrations.AddField(
            model_name='productreviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.products'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laptopproduct',
            name='laptop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_product', to='product.productvariations'),
        ),
        migrations.AddField(
            model_name='extraatrributefields',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_extra_attribute', to='product.productvariations'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product.productcomment'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combodiscount',
            name='products',
            field=models.ManyToManyField(related_name='combo_discounts', to='product.products'),
        ),
        migrations.AddField(
            model_name='businessproductdetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_product', to='product.products'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='product_pro_search__d1697d_gin'),
        ),
    ]
