/**
 * Common Indian Districts and Cities
 * This is a fallback list when API endpoints are not available
 * Based on common Indian administrative divisions
 */

export const INDIAN_DISTRICTS = [
  // Telangana
  "Hyderabad",
  "Rangareddy",
  "Medchal-Malkajgiri",
  "Sangareddy",
  "Vikarabad",
  "Mahabubnagar",
  "Nagarkurnool",
  "Wanaparthy",
  "Jogulamba Gadwal",
  "Narayanpet",
  "Nalgonda",
  "Suryapet",
  "Yadadri Bhuvanagiri",
  "Mahabubabad",
  "Warangal Urban",
  "Warangal Rural",
  "Jangaon",
  "Jayashankar Bhupalpally",
  "Mulugu",
  "Bhadradri Kothagudem",
  "Khammam",
  "Nizamabad",
  "Kamareddy",
  "Mancherial",
  "Peddapalli",
  "Karimnagar",
  "Rajanna Sircilla",
  "Jagtial",
  "Adilabad",
  "Kumram Bheem Asifabad",
  "Nirmal",
  
  // Maharashtra
  "Mumbai",
  "Pune",
  "Nagpur",
  "Thane",
  "Nashik",
  "Aurangabad",
  "Solapur",
  "Kolhapur",
  "Sangli",
  "Satara",
  "Ratnagiri",
  "Raigad",
  "Ahmednagar",
  "Jalgaon",
  "Dhule",
  "Nandurbar",
  "Amravati",
  "Yavatmal",
  "Wardha",
  "Chandrapur",
  "Gadchiroli",
  "Bhandara",
  "Gondia",
  
  // Karnataka
  "Bangalore Urban",
  "Bangalore Rural",
  "Mysore",
  "Mangalore",
  "Hubli",
  "Belgaum",
  "Gulbarga",
  "Davangere",
  "Bellary",
  "Bijapur",
  "Raichur",
  "Tumkur",
  "Shimoga",
  "Udupi",
  "Chikmagalur",
  "Hassan",
  "Mandya",
  "Kolar",
  "Chikkaballapur",
  "Tumakuru",
  
  // Tamil Nadu
  "Chennai",
  "Coimbatore",
  "Madurai",
  "Tiruchirappalli",
  "Salem",
  "Tirunelveli",
  "Erode",
  "Vellore",
  "Dindigul",
  "Thanjavur",
  "Tuticorin",
  "Kanchipuram",
  "Tiruvallur",
  "Krishnagiri",
  "Dharmapuri",
  "Namakkal",
  "Karur",
  "Pudukkottai",
  "Sivaganga",
  "Ramanathapuram",
  
  // Delhi
  "Central Delhi",
  "North Delhi",
  "South Delhi",
  "East Delhi",
  "West Delhi",
  "New Delhi",
  "North East Delhi",
  "North West Delhi",
  "Shahdara",
  "South East Delhi",
  "South West Delhi",
  
  // Gujarat
  "Ahmedabad",
  "Surat",
  "Vadodara",
  "Rajkot",
  "Bhavnagar",
  "Jamnagar",
  "Gandhinagar",
  "Anand",
  "Bharuch",
  "Kutch",
  "Mehsana",
  "Patan",
  "Banaskantha",
  "Sabarkantha",
  "Aravalli",
  
  // West Bengal
  "Kolkata",
  "Howrah",
  "Hooghly",
  "North 24 Parganas",
  "South 24 Parganas",
  "Nadia",
  "Murshidabad",
  "Bardhaman",
  "Birbhum",
  "Bankura",
  "Purulia",
  "Medinipur",
  "Jalpaiguri",
  "Darjeeling",
  "Cooch Behar",
  
  // Rajasthan
  "Jaipur",
  "Jodhpur",
  "Kota",
  "Bikaner",
  "Ajmer",
  "Udaipur",
  "Bhilwara",
  "Alwar",
  "Bharatpur",
  "Sikar",
  "Jhunjhunu",
  "Churu",
  "Nagaur",
  "Pali",
  "Barmer",
  
  // Uttar Pradesh
  "Lucknow",
  "Kanpur",
  "Agra",
  "Varanasi",
  "Allahabad",
  "Meerut",
  "Ghaziabad",
  "Noida",
  "Bareilly",
  "Aligarh",
  "Moradabad",
  "Saharanpur",
  "Gorakhpur",
  "Faizabad",
  "Mathura",
  
  // Andhra Pradesh
  "Visakhapatnam",
  "Vijayawada",
  "Guntur",
  "Nellore",
  "Kurnool",
  "Kadapa",
  "Anantapur",
  "Chittoor",
  "Tirupati",
  "Rajahmundry",
  "Eluru",
  "Ongole",
  "Machilipatnam",
  "Srikakulam",
  "Vizianagaram",
  
  // Kerala
  "Thiruvananthapuram",
  "Kochi",
  "Kozhikode",
  "Thrissur",
  "Kannur",
  "Kollam",
  "Alappuzha",
  "Palakkad",
  "Malappuram",
  "Ernakulam",
  "Idukki",
  "Kottayam",
  "Pathanamthitta",
  "Wayanad",
  "Kasaragod",
  
  // Punjab
  "Amritsar",
  "Ludhiana",
  "Jalandhar",
  "Patiala",
  "Bathinda",
  "Hoshiarpur",
  "Mohali",
  "Ferozepur",
  "Muktsar",
  "Mansa",
  "Sangrur",
  "Barnala",
  "Fatehgarh Sahib",
  "Rupnagar",
  "Gurdaspur",
  
  // Haryana
  "Gurgaon",
  "Faridabad",
  "Panipat",
  "Ambala",
  "Yamunanagar",
  "Karnal",
  "Sonipat",
  "Rohtak",
  "Hisar",
  "Sirsa",
  "Bhiwani",
  "Rewari",
  "Palwal",
  "Nuh",
  "Jhajjar",
  
  // Madhya Pradesh
  "Bhopal",
  "Indore",
  "Gwalior",
  "Jabalpur",
  "Ujjain",
  "Sagar",
  "Ratlam",
  "Satna",
  "Rewa",
  "Chhindwara",
  "Betul",
  "Sehore",
  "Raisen",
  "Vidisha",
  "Dewas",
  
  // Bihar
  "Patna",
  "Gaya",
  "Bhagalpur",
  "Muzaffarpur",
  "Darbhanga",
  "Purnia",
  "Sitamarhi",
  "Saran",
  "Siwan",
  "Vaishali",
  "Nalanda",
  "Bhojpur",
  "Rohtas",
  "Aurangabad (Bihar)",
  "Gopalganj",
  
  // Odisha
  "Bhubaneswar",
  "Cuttack",
  "Rourkela",
  "Brahmapur",
  "Sambalpur",
  "Puri",
  "Balasore",
  "Bhadrak",
  "Jagatsinghpur",
  "Kendujhar",
  "Mayurbhanj",
  "Dhenkanal",
  "Angul",
  "Nayagarh",
  "Khordha",
  
  // Assam
  "Guwahati",
  "Silchar",
  "Dibrugarh",
  "Jorhat",
  "Nagaon",
  "Tinsukia",
  "Tezpur",
  "Barpeta",
  "Goalpara",
  "Dhubri",
  "Kokrajhar",
  "Bongaigaon",
  "Darrang",
  "Sonitpur",
  "Lakhimpur",
  
  // Jharkhand
  "Ranchi",
  "Jamshedpur",
  "Dhanbad",
  "Bokaro",
  "Hazaribagh",
  "Giridih",
  "Deoghar",
  "Dumka",
  "Palamu",
  "Garhwa",
  "Latehar",
  "Chatra",
  "Koderma",
  "Gumla",
  "Simdega",
  
  // Chhattisgarh
  "Raipur",
  "Bhilai",
  "Bilaspur",
  "Durg",
  "Rajnandgaon",
  "Raigarh",
  "Korba",
  "Jagdalpur",
  "Ambikapur",
  "Dhamtari",
  "Mahasamund",
  "Balod",
  "Bemetara",
  "Baloda Bazar",
  "Gariaband",
  
  // Uttarakhand
  "Dehradun",
  "Haridwar",
  "Nainital",
  "Almora",
  "Pithoragarh",
  "Udham Singh Nagar",
  "Chamoli",
  "Rudraprayag",
  "Tehri Garhwal",
  "Uttarkashi",
  "Pauri Garhwal",
  "Champawat",
  "Bageshwar",
  
  // Himachal Pradesh
  "Shimla",
  "Kullu",
  "Mandi",
  "Solan",
  "Kangra",
  "Una",
  "Hamirpur",
  "Bilaspur",
  "Chamba",
  "Sirmaur",
  "Kinnaur",
  "Lahaul and Spiti",
  
  // Goa
  "North Goa",
  "South Goa",
  
  // Manipur
  "Imphal East",
  "Imphal West",
  "Thoubal",
  "Bishnupur",
  "Churachandpur",
  "Chandel",
  "Senapati",
  "Tamenglong",
  "Ukhrul",
  "Kangpokpi",
  
  // Meghalaya
  "East Khasi Hills",
  "West Khasi Hills",
  "Ri Bhoi",
  "East Jaintia Hills",
  "West Jaintia Hills",
  "East Garo Hills",
  "West Garo Hills",
  "South Garo Hills",
  "North Garo Hills",
  
  // Mizoram
  "Aizawl",
  "Lunglei",
  "Champhai",
  "Serchhip",
  "Lawngtlai",
  "Mamit",
  "Kolasib",
  "Saiha",
  
  // Nagaland
  "Kohima",
  "Dimapur",
  "Mokokchung",
  "Tuensang",
  "Wokha",
  "Zunheboto",
  "Phek",
  "Mon",
  "Kiphire",
  "Longleng",
  "Peren",
  
  // Tripura
  "West Tripura",
  "South Tripura",
  "Dhalai",
  "North Tripura",
  "Khowai",
  "Sepahijala",
  "Unakoti",
  "Gomati",
  
  // Sikkim
  "East Sikkim",
  "West Sikkim",
  "North Sikkim",
  "South Sikkim",
  
  // Arunachal Pradesh
  "Papum Pare",
  "Changlang",
  "Lohit",
  "Dibang Valley",
  "Lower Dibang Valley",
  "East Siang",
  "West Siang",
  "Upper Siang",
  "Tawang",
  "West Kameng",
  "East Kameng",
  "Lower Subansiri",
  "Upper Subansiri",
  "Kurung Kumey",
  "Kra Daadi",
  "Anjaw",
  "Longding",
  "Namsai",
  "Siang",
  "Lower Siang",
  "Lepa Rada",
  "Shi Yomi",
  "Pakke Kessang",
  "Kamle",
  
  // Andaman and Nicobar
  "South Andaman",
  "North and Middle Andaman",
  "Nicobar",
  
  // Dadra and Nagar Haveli and Daman and Diu
  "Dadra and Nagar Haveli",
  "Daman",
  "Diu",
  
  // Lakshadweep
  "Lakshadweep",
  
  // Ladakh
  "Leh",
  "Kargil",
  
  // Puducherry
  "Puducherry",
  "Karaikal",
  "Mahe",
  "Yanam",
];

export const INDIAN_CITIES = [
  // Major Cities
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Surat",
  "Pune",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Varanasi",
  "Srinagar",
  "Amritsar",
  "Chandigarh",
  "Jabalpur",
  "Gwalior",
  "Jodhpur",
  "Raipur",
  "Kota",
  "Guwahati",
  "Thiruvananthapuram",
  "Kochi",
  "Coimbatore",
  "Madurai",
  "Tiruchirappalli",
  "Salem",
  "Tirunelveli",
  "Erode",
  "Vellore",
  "Dindigul",
  "Thanjavur",
  "Tuticorin",
  "Kanchipuram",
  "Tiruvallur",
  "Krishnagiri",
  "Dharmapuri",
  "Namakkal",
  "Karur",
  "Pudukkottai",
  "Sivaganga",
  "Ramanathapuram",
  "Vijayawada",
  "Guntur",
  "Nellore",
  "Kurnool",
  "Kadapa",
  "Anantapur",
  "Chittoor",
  "Tirupati",
  "Rajahmundry",
  "Eluru",
  "Ongole",
  "Machilipatnam",
  "Srikakulam",
  "Vizianagaram",
  "Warangal",
  "Nizamabad",
  "Karimnagar",
  "Ramagundam",
  "Khammam",
  "Mahabubnagar",
  "Nalgonda",
  "Adilabad",
  "Suryapet",
  "Miryalaguda",
  "Jagtial",
  "Mancherial",
  "Peddapalli",
  "Bodhan",
  "Kamareddy",
  "Medak",
  "Siddipet",
  "Zaheerabad",
  "Sangareddy",
  "Medchal",
  "Malkajgiri",
  "Quthbullapur",
  "Serilingampally",
  "Rajendranagar",
  "Shamshabad",
  "Ibrahimpatnam",
  "Maheshwaram",
  "Yacharam",
  "Kandukur",
  "Kothur",
  "Shadnagar",
  "Keshampet",
  "Tandur",
  "Vikarabad",
  "Pargi",
  "Dharur",
  "Bidar",
  "Bhalki",
  "Aurad",
  "Basavakalyan",
  "Humnabad",
  "Chitguppa",
  "Kamalnagar",
  "Homnabad",
  "Gulbarga",
  "Aland",
  "Afzalpur",
  "Jevargi",
  "Sedam",
  "Chitapur",
  "Kalaburagi",
  "Yadgir",
  "Shahpur",
  "Shorapur",
  "Shahbad",
  "Wadi",
  "Chincholi",
  "Gurmatkal",
  "Surapur",
  "Shahpur",
  "Yadgir",
  "Shorapur",
  "Shahbad",
  "Wadi",
  "Chincholi",
  "Gurmatkal",
  "Surapur",
];

/**
 * Get cities for a specific district
 * This is a simplified mapping - in production, this should come from backend
 */
export const getCitiesForDistrict = (district) => {
  if (!district) return INDIAN_CITIES;
  
  const districtLower = district.toLowerCase();
  
  // Map districts to their major cities
  const districtCityMap = {
    "hyderabad": ["Hyderabad", "Secunderabad", "Old City", "HITEC City"],
    "rangareddy": ["Hyderabad", "Secunderabad", "Gachibowli", "Kondapur", "Madhapur"],
    "medchal-malkajgiri": ["Hyderabad", "Medchal", "Malkajgiri", "Quthbullapur"],
    "mumbai": ["Mumbai", "Navi Mumbai", "Thane"],
    "pune": ["Pune", "Pimpri-Chinchwad", "Hinjewadi"],
    "bangalore urban": ["Bangalore", "Bengaluru"],
    "chennai": ["Chennai", "Tambaram", "Ambattur"],
    "kolkata": ["Kolkata", "Howrah"],
    "delhi": ["New Delhi", "Delhi"],
    "ahmedabad": ["Ahmedabad", "Gandhinagar"],
    "surat": ["Surat", "Bardoli"],
    "jaipur": ["Jaipur", "Sanganer"],
    "lucknow": ["Lucknow", "Barabanki"],
    "kanpur": ["Kanpur", "Unnao"],
    "nagpur": ["Nagpur", "Wardha"],
    "indore": ["Indore", "Dewas"],
    "visakhapatnam": ["Visakhapatnam", "Vizag"],
    "vijayawada": ["Vijayawada", "Guntur"],
    "coimbatore": ["Coimbatore", "Tiruppur"],
    "madurai": ["Madurai", "Dindigul"],
    "kochi": ["Kochi", "Ernakulam"],
    "thiruvananthapuram": ["Thiruvananthapuram", "Kovalam"],
  "bhopal": ["Bhopal", "Sehore"],
  "patna": ["Patna", "Hajipur"],
  "bhojpur": ["Bhojpur", "Arrah", "Jagdishpur"],
  "raipur": ["Raipur", "Bhilai"],
    "jodhpur": ["Jodhpur", "Pali"],
    "kota": ["Kota", "Bundi"],
    "guwahati": ["Guwahati", "Dispur"],
    "dehradun": ["Dehradun", "Haridwar"],
    "shimla": ["Shimla", "Kullu"],
    "ranchi": ["Ranchi", "Jamshedpur"],
    "bhubaneswar": ["Bhubaneswar", "Cuttack"],
  };
  
  // Try exact match first
  if (districtCityMap[districtLower]) {
    return districtCityMap[districtLower];
  }
  
  // Try partial match
  for (const [key, cities] of Object.entries(districtCityMap)) {
    if (districtLower.includes(key) || key.includes(districtLower)) {
      return cities;
    }
  }
  
  // Default: return all cities
  return INDIAN_CITIES;
};

