# Generated by Django 4.2.11 on 2025-11-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_token', models.CharField(max_length=20, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=120, null=True)),
                ('order_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='orders.orders')),
            ],
        ),
    ]
